'use client';

import { useState, useEffect } from 'react';
import { 
  FileText, 
  Plus, 
  Download, 
  RefreshCw,
  CreditCard,
  Check,
  Clock,
  AlertTriangle,
  X,
  Sparkles,
  ExternalLink,
  Trash2,
  Send,
  Eye,
} from 'lucide-react';
import { motion, AnimatePresence, Variants } from 'framer-motion';
import { cn } from '@/lib/utils';
import { useToast } from '@/lib/useToast';
import { useData } from '@/lib/DataContext';

const containerVariants: Variants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.04 }
  }
};

const itemVariants: Variants = {
  hidden: { opacity: 0, y: 8 },
  show: { 
    opacity: 1, 
    y: 0,
    transition: { type: 'spring', stiffness: 400, damping: 30 }
  }
};

const STATUS_COLORS: Record<string, string> = {
  draft: 'text-silver bg-silver/10 border-silver/20',
  sent: 'text-blue-500 bg-blue-500/10 border-blue-500/20',
  viewed: 'text-purple-500 bg-purple-500/10 border-purple-500/20',
  paid: 'text-emerald-500 bg-emerald-500/10 border-emerald-500/20',
  overdue: 'text-red-500 bg-red-500/10 border-red-500/20',
  cancelled: 'text-silver bg-silver/10 border-silver/20',
};

export default function InvoicesPage() {
  const { sub, loading: loadingSub } = useData();
  const [invoices, setInvoices] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalInvoices, setTotalInvoices] = useState(0);
  const [statusFilter, setStatusFilter] = useState('all');
  const [selectedInvoice, setSelectedInvoice] = useState<any>(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showAIModal, setShowAIModal] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [generatingAI, setGeneratingAI] = useState(false);
  const { showToast, Toast } = useToast();

  // Create form state
  const [newInvoice, setNewInvoice] = useState({
    title: '',
    description: '',
    items: [{ name: '', description: '', quantity: 1, unitPrice: 0 }],
    taxRate: 0,
    customerName: '',
    customerEmail: '',
    customerPhone: '',
    notes: '',
  });

  const fetchInvoices = async (targetPage = 1) => {
    try {
      const res = await fetch(`/api/invoices?page=${targetPage}&limit=20&status=${statusFilter}`);
      if (res.ok) {
        const data = await res.json();
        setInvoices(data.invoices || []);
        setPage(data.page || 1);
        setTotalPages(data.pages || 1);
        setTotalInvoices(data.total || 0);
      }
    } catch (err) {
      console.error('Failed to fetch invoices:', err);
      showToast('Failed to load invoices', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!loadingSub) {
      fetchInvoices(1);
    }
  }, [statusFilter, loadingSub]);

  const [creating, setCreating] = useState(false);

  const handleCreateInvoice = async () => {
    try {
      const items = newInvoice.items
        .filter(item => item.name && item.unitPrice > 0)
        .map(item => ({
          ...item,
          total: item.quantity * item.unitPrice,
        }));

      if (items.length === 0) {
        showToast('Add at least one item', 'error');
        return;
      }

      setCreating(true);
      const res = await fetch('/api/invoices', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...newInvoice,
          items,
          customer: {
            name: newInvoice.customerName,
            email: newInvoice.customerEmail,
            phone: newInvoice.customerPhone,
          },
        }),
      });

      if (res.ok) {
        showToast('Invoice created');
        setShowCreateModal(false);
        fetchInvoices(page);
        resetForm();
      } else {
        const data = await res.json().catch(() => ({}));
        showToast(data.error || 'Failed to create invoice', 'error');
      }
    } catch (err) {
      showToast('Failed to create invoice', 'error');
    } finally {
      setCreating(false);
    }
  };

  const handleGenerateAI = async () => {
    if (!aiPrompt.trim()) {
      showToast('Enter a description for the invoice', 'error');
      return;
    }

    setGeneratingAI(true);
    try {
      const res = await fetch('/api/invoices/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: aiPrompt }),
      });

      if (res.ok) {
        showToast('Invoice generated by AI');
        setShowAIModal(false);
        setAiPrompt('');
        fetchInvoices(page);
      }
    } catch (err) {
      showToast('Failed to generate invoice', 'error');
    } finally {
      setGeneratingAI(false);
    }
  };

  const handleCreatePaymentLink = async (invoiceId: string) => {
    try {
      const res = await fetch('/api/invoices', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: invoiceId, createPaymentLink: true, status: 'sent' }),
      });

      if (res.ok) {
        const data = await res.json();
        showToast('Payment link created');
        if (data.stripePaymentLinkUrl) {
          window.open(data.stripePaymentLinkUrl, '_blank');
        }
        fetchInvoices(page);
      }
    } catch (err) {
      showToast('Failed to create payment link', 'error');
    }
  };

  const handleDeleteInvoice = async (id: string) => {
    if (!confirm('Delete this invoice?')) return;
    
    try {
      const res = await fetch(`/api/invoices?id=${id}`, { method: 'DELETE' });
      if (res.ok) {
        showToast('Invoice deleted');
        setSelectedInvoice(null);
        fetchInvoices(page);
      }
    } catch (err) {
      showToast('Failed to delete invoice', 'error');
    }
  };

  const resetForm = () => {
    setNewInvoice({
      title: '',
      description: '',
      items: [{ name: '', description: '', quantity: 1, unitPrice: 0 }],
      taxRate: 0,
      customerName: '',
      customerEmail: '',
      customerPhone: '',
      notes: '',
    });
  };

  const downloadInvoicePDF = (invoice: any) => {
    // Generate a simple HTML invoice and open in new window for printing
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Invoice ${invoice.invoiceNumber}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
          .title { font-size: 28px; font-weight: bold; color: #333; }
          .invoice-number { color: #666; margin-top: 8px; }
          .status { padding: 4px 12px; border-radius: 4px; font-size: 12px; font-weight: bold; text-transform: uppercase; }
          .status.paid { background: #d1fae5; color: #059669; }
          .status.sent { background: #dbeafe; color: #2563eb; }
          .status.draft { background: #f3f4f6; color: #6b7280; }
          table { width: 100%; border-collapse: collapse; margin: 30px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
          th { background: #f9fafb; font-weight: 600; font-size: 12px; text-transform: uppercase; color: #6b7280; }
          .total-row { font-weight: bold; font-size: 16px; }
          .notes { margin-top: 30px; padding: 20px; background: #f9fafb; border-radius: 8px; font-size: 14px; color: #6b7280; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="title">INVOICE</div>
            <div class="invoice-number">${invoice.invoiceNumber}</div>
          </div>
          <div>
            <span class="status ${invoice.status}">${invoice.status}</span>
            <div style="margin-top: 16px; font-size: 14px; color: #666;">
              <div>Date: ${new Date(invoice.issuedAt).toLocaleDateString()}</div>
              ${invoice.dueAt ? `<div>Due: ${new Date(invoice.dueAt).toLocaleDateString()}</div>` : ''}
            </div>
          </div>
        </div>
        
        ${invoice.customer?.name ? `
          <div style="margin-bottom: 30px;">
            <div style="font-size: 12px; color: #6b7280; text-transform: uppercase; margin-bottom: 8px;">Bill To</div>
            <div style="font-weight: 600;">${invoice.customer.name}</div>
            ${invoice.customer.email ? `<div style="color: #666;">${invoice.customer.email}</div>` : ''}
            ${invoice.customer.phone ? `<div style="color: #666;">${invoice.customer.phone}</div>` : ''}
          </div>
        ` : ''}

        <div style="font-size: 18px; font-weight: 600; margin-bottom: 8px;">${invoice.title}</div>
        ${invoice.description ? `<div style="color: #666; margin-bottom: 24px;">${invoice.description}</div>` : ''}

        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th>Qty</th>
              <th>Unit Price</th>
              <th style="text-align: right;">Total</th>
            </tr>
          </thead>
          <tbody>
            ${invoice.items.map((item: any) => `
              <tr>
                <td>
                  <div style="font-weight: 600;">${item.name}</div>
                  ${item.description ? `<div style="font-size: 12px; color: #666;">${item.description}</div>` : ''}
                </td>
                <td>${item.quantity}</td>
                <td>$${item.unitPrice.toFixed(2)}</td>
                <td style="text-align: right;">$${item.total.toFixed(2)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div style="text-align: right; margin-top: 20px;">
          <div style="margin-bottom: 8px;">Subtotal: $${invoice.subtotal.toFixed(2)}</div>
          ${invoice.taxRate > 0 ? `<div style="margin-bottom: 8px;">Tax (${invoice.taxRate}%): $${invoice.taxAmount.toFixed(2)}</div>` : ''}
          <div class="total-row" style="font-size: 20px; margin-top: 16px; padding-top: 16px; border-top: 2px solid #333;">
            Total: $${invoice.total.toFixed(2)} ${invoice.currency}
          </div>
        </div>

        ${invoice.notes ? `<div class="notes"><strong>Notes:</strong> ${invoice.notes}</div>` : ''}
        ${invoice.stripePaymentLinkUrl ? `<div style="margin-top: 20px; text-align: center;"><a href="${invoice.stripePaymentLinkUrl}" style="display: inline-block; padding: 12px 24px; background: #3b82f6; color: white; text-decoration: none; border-radius: 8px; font-weight: 600;">Pay Now</a></div>` : ''}
      </body>
      </html>
    `;
    
    const newWindow = window.open('', '_blank');
    if (newWindow) {
      newWindow.document.write(html);
      newWindow.document.close();
    }
  };

  const totalRevenue = invoices.filter(i => i.status === 'paid').reduce((sum, i) => sum + i.total, 0);
  const pendingAmount = invoices.filter(i => ['sent', 'viewed'].includes(i.status)).reduce((sum, i) => sum + i.total, 0);

  return (
    <div className="space-y-8 font-sans antialiased">
      {Toast}

      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="show"
        className="space-y-8"
      >
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-5 border-b border-border-default pb-6">
          <div className="space-y-1">
            <div className="flex items-center gap-3">
              <h1 className="text-xl md:text-2xl font-semibold tracking-tight text-foreground">
                AI Invoicing
              </h1>
              <div className="flex items-center gap-1.5 px-2.5 py-0.5 bg-emerald-500/10 border border-emerald-500/15 rounded-full">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 relative flex shrink-0">
                  <span className="absolute inline-flex h-full w-full rounded-full bg-emerald-500 opacity-75 animate-ping" />
                </span>
                <span className="text-[9px] font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-widest">
                  Payment Engine Active
                </span>
              </div>
            </div>
            <p className="text-silver text-xs font-medium">
              Generate invoices with AI and collect payments via Stripe.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowAIModal(true)}
              className="flex items-center gap-2 px-4 py-2.5 bg-purple-500/10 border border-purple-500/20 text-purple-500 rounded-xl text-xs font-bold hover:bg-purple-500/20 transition-all"
            >
              <Sparkles className="w-3.5 h-3.5" />
              Generate with AI
            </button>
            <button
              onClick={() => setShowCreateModal(true)}
              className="flex items-center gap-2 px-4 py-2.5 bg-foreground text-background rounded-xl text-xs font-bold hover:opacity-90 transition-all"
            >
              <Plus className="w-3.5 h-3.5" />
              Create Invoice
            </button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {[
            { label: 'Total Invoices', value: totalInvoices, icon: FileText, color: 'text-blue-500' },
            { label: 'Revenue Collected', value: `$${totalRevenue.toLocaleString()}`, icon: CreditCard, color: 'text-emerald-500' },
            { label: 'Pending Amount', value: `$${pendingAmount.toLocaleString()}`, icon: Clock, color: 'text-amber-500' },
            { label: 'Paid Rate', value: `${totalInvoices > 0 ? Math.round((invoices.filter(i => i.status === 'paid').length / totalInvoices) * 100) : 0}%`, icon: Check, color: 'text-purple-500' },
          ].map((stat, i) => (
            <motion.div key={i} variants={itemVariants} className="bg-bg-subtle border border-border-default rounded-2xl p-5">
              <div className="flex items-center gap-3">
                <stat.icon className={cn("w-5 h-5", stat.color)} />
                <div>
                  <p className="text-lg font-bold text-foreground">{loading ? '—' : stat.value}</p>
                  <p className="text-[10px] font-bold text-silver uppercase tracking-wider">{stat.label}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Filter Bar */}
        <div className="flex items-center gap-2 p-1 bg-bg-elevated border border-border-default rounded-xl w-fit">
          {['all', 'draft', 'sent', 'paid', 'overdue'].map((status) => (
            <button
              key={status}
              onClick={() => setStatusFilter(status)}
              className={cn(
                "px-3 py-1.5 rounded-lg text-[10px] font-bold uppercase transition-all",
                statusFilter === status
                  ? "bg-foreground text-background"
                  : "text-silver hover:text-foreground"
              )}
            >
              {status}
            </button>
          ))}
        </div>

        {/* Invoices List */}
        {loading ? (
          <div className="space-y-3">
            {[1, 2, 3].map(i => (
              <div key={i} className="h-24 bg-bg-surface border border-border-subtle rounded-xl animate-pulse" />
            ))}
          </div>
        ) : invoices.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 bg-bg-subtle border border-border-default border-dashed rounded-2xl">
            <FileText className="w-12 h-12 text-silver mb-3" />
            <h3 className="text-sm font-semibold text-foreground">No invoices yet</h3>
            <p className="text-silver text-xs mt-1">Create your first invoice or let AI generate one.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {invoices.map((invoice) => (
              <motion.div
                key={invoice._id}
                variants={itemVariants}
                onClick={() => setSelectedInvoice(invoice)}
                className="bg-bg-subtle hover:bg-bg-elevated border border-border-default hover:border-border-hover rounded-xl px-5 py-4 transition-all cursor-pointer"
              >
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
                  <div className="flex items-center gap-4">
                    <div className="w-10 h-10 bg-bg-elevated border border-border-strong rounded-xl flex items-center justify-center">
                      <FileText className="w-5 h-5 text-silver" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="font-semibold text-sm text-foreground">{invoice.title}</h3>
                        {invoice.generatedByAI && (
                          <span className="text-[8px] px-1.5 py-0.5 bg-purple-500/10 text-purple-500 rounded font-bold">AI</span>
                        )}
                      </div>
                      <p className="text-[10px] text-silver font-mono">{invoice.invoiceNumber} • {invoice.customer?.name || 'No customer'}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-4">
                    <div className="text-right">
                      <p className="text-lg font-bold text-foreground">${invoice.total.toFixed(2)}</p>
                      <p className="text-[10px] text-silver">{new Date(invoice.issuedAt).toLocaleDateString()}</p>
                    </div>
                    <span className={cn("px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase border", STATUS_COLORS[invoice.status])}>
                      {invoice.status}
                    </span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        )}

        {/* Pagination */}
        {!loading && totalPages > 1 && (
          <div className="flex items-center justify-center gap-4">
            <button
              onClick={() => fetchInvoices(page - 1)}
              disabled={page <= 1}
              className="px-3 py-1.5 bg-bg-elevated border border-border-default rounded-lg text-xs font-bold text-silver hover:text-foreground disabled:opacity-40"
            >
              Previous
            </button>
            <span className="text-xs font-bold text-foreground">Page {page} of {totalPages}</span>
            <button
              onClick={() => fetchInvoices(page + 1)}
              disabled={page >= totalPages}
              className="px-3 py-1.5 bg-bg-elevated border border-border-default rounded-lg text-xs font-bold text-silver hover:text-foreground disabled:opacity-40"
            >
              Next
            </button>
          </div>
        )}

      </motion.div>

      {/* AI Generation Modal */}
      <AnimatePresence>
        {showAIModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-background border border-border-default rounded-2xl p-6 w-full max-w-md mx-4 shadow-2xl"
            >
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-sm font-bold text-foreground flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-purple-500" />
                  Generate Invoice with AI
                </h2>
                <button onClick={() => setShowAIModal(false)} className="p-1 hover:bg-bg-elevated rounded-lg">
                  <X className="w-4 h-4 text-silver" />
                </button>
              </div>
              
              <textarea
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="Describe the services or products to invoice for...&#10;&#10;Example: Website design and development for a restaurant, including logo design, 5 pages, and SEO optimization"
                className="w-full h-32 bg-bg-elevated border border-border-default rounded-xl px-4 py-3 text-xs text-foreground placeholder:text-silver/40 focus:outline-none focus:border-purple-500/40 resize-none"
              />

              <div className="flex gap-2 mt-4">
                <button
                  onClick={() => setShowAIModal(false)}
                  className="flex-1 px-4 py-2.5 bg-bg-elevated border border-border-default rounded-xl text-xs font-bold text-silver hover:text-foreground"
                >
                  Cancel
                </button>
                <button
                  onClick={handleGenerateAI}
                  disabled={generatingAI || !aiPrompt.trim()}
                  className="flex-1 px-4 py-2.5 bg-purple-500 text-white rounded-xl text-xs font-bold hover:bg-purple-600 disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {generatingAI ? (
                    <>
                      <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5" />
                      Generate
                    </>
                  )}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Create Invoice Modal */}
      <AnimatePresence>
        {showCreateModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-background border border-border-default rounded-2xl p-6 w-full max-w-2xl mx-4 my-8 shadow-2xl"
            >
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-sm font-bold text-foreground">Create Invoice</h2>
                <button onClick={() => setShowCreateModal(false)} className="p-1 hover:bg-bg-elevated rounded-lg">
                  <X className="w-4 h-4 text-silver" />
                </button>
              </div>

              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-1">Title</label>
                    <input
                      type="text"
                      value={newInvoice.title}
                      onChange={(e) => setNewInvoice({ ...newInvoice, title: e.target.value })}
                      placeholder="Invoice title"
                      className="w-full bg-bg-elevated border border-border-default rounded-xl px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-border-hover"
                    />
                  </div>
                  <div>
                    <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-1">Tax Rate (%)</label>
                    <input
                      type="number"
                      value={newInvoice.taxRate}
                      onChange={(e) => setNewInvoice({ ...newInvoice, taxRate: parseFloat(e.target.value) || 0 })}
                      className="w-full bg-bg-elevated border border-border-default rounded-xl px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-border-hover"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-1">Description</label>
                  <input
                    type="text"
                    value={newInvoice.description}
                    onChange={(e) => setNewInvoice({ ...newInvoice, description: e.target.value })}
                    placeholder="Brief description"
                    className="w-full bg-bg-elevated border border-border-default rounded-xl px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-border-hover"
                  />
                </div>

                <div className="border-t border-border-default pt-4">
                  <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-2">Line Items</label>
                  {newInvoice.items.map((item, idx) => (
                    <div key={idx} className="mb-3">
                      <div className="flex gap-2 mb-1">
                        <input
                          type="text"
                          value={item.name}
                          onChange={(e) => {
                            const items = [...newInvoice.items];
                            items[idx].name = e.target.value;
                            setNewInvoice({ ...newInvoice, items });
                          }}
                          placeholder="e.g. Website Design, Logo, Consulting"
                          className="flex-1 bg-bg-elevated border border-border-default rounded-lg px-3 py-2 text-xs text-foreground focus:outline-none"
                        />
                        <input
                          type="number"
                          value={item.quantity}
                          onChange={(e) => {
                            const items = [...newInvoice.items];
                            items[idx].quantity = parseInt(e.target.value) || 1;
                            setNewInvoice({ ...newInvoice, items });
                          }}
                          placeholder="Qty"
                          className="w-16 bg-bg-elevated border border-border-default rounded-lg px-3 py-2 text-xs text-foreground focus:outline-none"
                        />
                        <input
                          type="number"
                          value={item.unitPrice}
                          onChange={(e) => {
                            const items = [...newInvoice.items];
                            items[idx].unitPrice = parseFloat(e.target.value) || 0;
                            setNewInvoice({ ...newInvoice, items });
                          }}
                          placeholder="$0.00"
                          className="w-24 bg-bg-elevated border border-border-default rounded-lg px-3 py-2 text-xs text-foreground focus:outline-none"
                        />
                      </div>
                      <div className="flex gap-2">
                        <span className="flex-1 text-[9px] text-silver font-medium">Service or product name</span>
                        <span className="w-16 text-[9px] text-silver font-medium text-center">Quantity</span>
                        <span className="w-24 text-[9px] text-silver font-medium text-right">Unit price</span>
                      </div>
                    </div>
                  ))}
                  <button
                    onClick={() => setNewInvoice({ ...newInvoice, items: [...newInvoice.items, { name: '', description: '', quantity: 1, unitPrice: 0 }] })}
                    className="text-[10px] text-purple-500 hover:text-purple-600 font-bold"
                  >
                    + Add Item
                  </button>
                </div>

                <div className="border-t border-border-default pt-4 grid grid-cols-3 gap-4">
                  <div>
                    <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-1">Customer Name</label>
                    <input
                      type="text"
                      value={newInvoice.customerName}
                      onChange={(e) => setNewInvoice({ ...newInvoice, customerName: e.target.value })}
                      className="w-full bg-bg-elevated border border-border-default rounded-lg px-3 py-2 text-xs text-foreground focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-1">Email</label>
                    <input
                      type="email"
                      value={newInvoice.customerEmail}
                      onChange={(e) => setNewInvoice({ ...newInvoice, customerEmail: e.target.value })}
                      className="w-full bg-bg-elevated border border-border-default rounded-lg px-3 py-2 text-xs text-foreground focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-1">Phone</label>
                    <input
                      type="tel"
                      value={newInvoice.customerPhone}
                      onChange={(e) => setNewInvoice({ ...newInvoice, customerPhone: e.target.value })}
                      className="w-full bg-bg-elevated border border-border-default rounded-lg px-3 py-2 text-xs text-foreground focus:outline-none"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-[10px] font-bold text-silver uppercase tracking-wider block mb-1">Notes</label>
                  <textarea
                    value={newInvoice.notes}
                    onChange={(e) => setNewInvoice({ ...newInvoice, notes: e.target.value })}
                    placeholder="Payment terms, thank you note, etc."
                    className="w-full h-20 bg-bg-elevated border border-border-default rounded-xl px-4 py-3 text-xs text-foreground placeholder:text-silver/40 focus:outline-none resize-none"
                  />
                </div>
              </div>

              <div className="flex gap-2 mt-6">
                <button
                  onClick={() => { setShowCreateModal(false); resetForm(); }}
                  className="flex-1 px-4 py-2.5 bg-bg-elevated border border-border-default rounded-xl text-xs font-bold text-silver hover:text-foreground"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleCreateInvoice}
                  disabled={!newInvoice.title || creating}
                  className="flex-1 px-4 py-2.5 bg-foreground text-background rounded-xl text-xs font-bold hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {creating ? (
                    <>
                      <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                      Creating...
                    </>
                  ) : (
                    'Create Invoice'
                  )}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Invoice Detail Drawer */}
      <AnimatePresence>
        {selectedInvoice && (
          <div className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedInvoice(null)}
              className="absolute inset-0"
            />
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', stiffness: 350, damping: 30 }}
              className="relative w-full max-w-lg bg-background border-l border-border-strong shadow-2xl h-full flex flex-col z-10"
            >
              <div className="p-6 border-b border-border-default flex justify-between items-center">
                <div>
                  <h2 className="text-sm font-bold text-foreground">{selectedInvoice.invoiceNumber}</h2>
                  <p className="text-[10px] text-silver">{selectedInvoice.title}</p>
                </div>
                <div className="flex items-center gap-2">
                  <span className={cn("px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase border", STATUS_COLORS[selectedInvoice.status])}>
                    {selectedInvoice.status}
                  </span>
                  <button onClick={() => setSelectedInvoice(null)} className="p-1 hover:bg-bg-elevated rounded-lg">
                    <X className="w-4 h-4 text-silver" />
                  </button>
                </div>
              </div>

              <div className="flex-1 overflow-y-auto p-6 space-y-6">
                {/* Amount */}
                <div className="text-center py-6 bg-bg-subtle rounded-2xl">
                  <p className="text-3xl font-bold text-foreground">${selectedInvoice.total.toFixed(2)}</p>
                  <p className="text-xs text-silver mt-1">{selectedInvoice.currency}</p>
                </div>

                {/* Customer */}
                {selectedInvoice.customer?.name && (
                  <div className="space-y-2">
                    <h4 className="text-[10px] font-bold text-silver uppercase tracking-wider">Customer</h4>
                    <div className="bg-bg-surface border border-border-default rounded-xl p-4 text-xs">
                      <p className="font-semibold text-foreground">{selectedInvoice.customer.name}</p>
                      {selectedInvoice.customer.email && <p className="text-silver">{selectedInvoice.customer.email}</p>}
                      {selectedInvoice.customer.phone && <p className="text-silver">{selectedInvoice.customer.phone}</p>}
                    </div>
                  </div>
                )}

                {/* Items */}
                <div className="space-y-2">
                  <h4 className="text-[10px] font-bold text-silver uppercase tracking-wider">Line Items</h4>
                  <div className="bg-bg-surface border border-border-default rounded-xl overflow-hidden">
                    {selectedInvoice.items.map((item: any, idx: number) => (
                      <div key={idx} className={cn("p-4 text-xs", idx > 0 && "border-t border-border-default")}>
                        <div className="flex justify-between">
                          <span className="font-semibold text-foreground">{item.name}</span>
                          <span className="text-foreground">${item.total.toFixed(2)}</span>
                        </div>
                        <p className="text-silver text-[10px] mt-0.5">{item.quantity} × ${item.unitPrice.toFixed(2)}</p>
                      </div>
                    ))}
                    <div className="p-4 border-t border-border-default bg-bg-elevated">
                      <div className="flex justify-between text-xs">
                        <span className="text-silver">Subtotal</span>
                        <span>${selectedInvoice.subtotal.toFixed(2)}</span>
                      </div>
                      {selectedInvoice.taxRate > 0 && (
                        <div className="flex justify-between text-xs mt-1">
                          <span className="text-silver">Tax ({selectedInvoice.taxRate}%)</span>
                          <span>${selectedInvoice.taxAmount.toFixed(2)}</span>
                        </div>
                      )}
                      <div className="flex justify-between text-sm font-bold mt-2 pt-2 border-t border-border-default">
                        <span>Total</span>
                        <span>${selectedInvoice.total.toFixed(2)}</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Notes */}
                {selectedInvoice.notes && (
                  <div className="space-y-2">
                    <h4 className="text-[10px] font-bold text-silver uppercase tracking-wider">Notes</h4>
                    <p className="text-xs text-silver bg-bg-surface border border-border-default rounded-xl p-4">{selectedInvoice.notes}</p>
                  </div>
                )}
              </div>

              <div className="p-4 border-t border-border-default flex gap-2">
                <button
                  onClick={() => downloadInvoicePDF(selectedInvoice)}
                  className="flex-1 px-4 py-2.5 bg-bg-elevated border border-border-default rounded-xl text-xs font-bold text-silver hover:text-foreground flex items-center justify-center gap-2"
                >
                  <Download className="w-3.5 h-3.5" /> Download
                </button>
                <button
                  onClick={() => handleCreatePaymentLink(selectedInvoice._id)}
                  disabled={selectedInvoice.stripePaymentLinkUrl}
                  className="flex-1 px-4 py-2.5 bg-blue-500 text-white rounded-xl text-xs font-bold hover:bg-blue-600 disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {selectedInvoice.stripePaymentLinkUrl ? (
                    <a href={selectedInvoice.stripePaymentLinkUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
                      <ExternalLink className="w-3.5 h-3.5" /> View Link
                    </a>
                  ) : (
                    <>
                      <CreditCard className="w-3.5 h-3.5" /> Create Payment Link
                    </>
                  )}
                </button>
                <button
                  onClick={() => handleDeleteInvoice(selectedInvoice._id)}
                  className="px-4 py-2.5 bg-red-500/10 text-red-500 border border-red-500/20 rounded-xl text-xs font-bold hover:bg-red-500/20"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
