'use client';

import { FileText } from 'lucide-react';
import PolicyLayout from '@/components/PolicyLayout';

const sections = [
  {
    title: '1. Agreement to Terms',
    content: `By accessing or using the VOID platform ("Service"), you agree to be bound by these Terms and Conditions. If you do not agree, do not use the Service. These Terms constitute a legally binding agreement between you and VOID, Inc.`
  },
  {
    title: '2. Description of Service',
    content: 'VOID provides an AI-powered workforce platform that enables businesses to deploy autonomous AI agents for customer support and sales, connect to messaging channels, capture leads, and generate invoices.'
  },
  {
    title: '3. Account Registration',
    items: [
      'You must be at least 18 years old to use VOID',
      'You are responsible for maintaining account security',
      'You must provide accurate and complete registration information',
      'You must notify us immediately of any unauthorized access'
    ]
  },
  {
    title: '4. Subscription Plans and Payment',
    subsections: [
      {
        heading: 'Plans',
        items: ['Free Trial: $0 — 14-day full access, no credit card required', 'Starter: $29/mo — 2 agents, 1,000 messages, core features', 'Pro: $99/mo — 5 agents, 5,000 messages, marketplace access', 'Enterprise: $299/mo — 20 agents, 25,000 messages, all features']
      },
      {
        heading: 'Billing',
        items: ['Subscriptions are billed monthly in advance', 'Payment is processed via Stripe', 'All fees are non-refundable except as required by law', 'Price changes take effect at the next billing cycle']
      }
    ]
  },
  {
    title: '5. Acceptable Use',
    subsections: [
      {
        heading: 'Permitted Use',
        items: ['Customer support automation', 'Sales lead capture and qualification', 'Internal communication assistance', 'Business process automation']
      },
      {
        heading: 'Prohibited Use',
        items: ['Sending spam, phishing, or deceptive messages', 'Violating any applicable law or regulation', 'Infringing on intellectual property rights', 'Reverse engineering or decompiling the Service', 'Reselling the Service without authorization']
      }
    ]
  },
  {
    title: '6. AI Agent Operations',
    items: [
      'AI agents are automated tools and may produce inaccurate responses',
      'You are responsible for monitoring AI agent performance',
      'You retain ownership of training data you provide',
      'You own the rights to outputs generated by your AI agents',
      'Human oversight is recommended for complex situations'
    ]
  },
  {
    title: '7. Data Ownership and Privacy',
    items: [
      'You retain all rights to your data',
      'We process your data solely to provide the Service',
      'You may export your data at any time',
      'Upon termination, data is deleted within 30 days'
    ]
  },
  {
    title: '8. Intellectual Property',
    subsections: [
      {
        heading: 'Our IP',
        items: ['VOID platform and its components', 'Source code and algorithms', 'Trademarks, logos, and branding', 'Documentation and materials']
      },
      {
        heading: 'Your IP',
        items: ['Business name and branding', 'Training content and knowledge base', 'Customer data', 'AI-generated outputs']
      }
    ]
  },
  {
    title: '9. Third-Party Integrations',
    items: [
      'Supported channels: WhatsApp, Telegram, Web Chat, Email',
      'Your use of third-party platforms is subject to their terms',
      'We are not responsible for third-party platform availability'
    ]
  },
  {
    title: '10. Service Level',
    items: [
      'We target 99.9% uptime for the platform',
      'Scheduled maintenance is announced in advance',
      'Enterprise customers may negotiate custom SLAs'
    ]
  },
  {
    title: '11. Limitation of Liability',
    content: 'THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES. TO THE MAXIMUM EXTENT PERMITTED BY LAW, VOID SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, OR DAMAGES EXCEEDING THE FEES PAID IN THE 12 MONTHS PRECEDING THE CLAIM.'
  },
  {
    title: '12. Indemnification',
    content: 'You agree to indemnify and hold harmless VOID from any claims arising from your use of the Service, violation of these Terms, violation of applicable laws, or content you provide to the Service.'
  },
  {
    title: '13. Termination',
    items: [
      'You may terminate your account at any time',
      'We may suspend or terminate for Terms violations or overdue payment',
      'Upon termination, data is retained for 30 days then deleted',
      'Outstanding fees remain payable after termination'
    ]
  },
  {
    title: '14. Dispute Resolution',
    items: [
      'Governed by the laws of the State of Delaware',
      'Disputes resolved through binding arbitration (AAA)',
      'Class action waiver applies'
    ]
  },
  {
    title: '15. Changes to Terms',
    content: 'We may update these Terms from time to time. Material changes will be notified at least 30 days in advance via email or platform notification.'
  },
  {
    title: '16. Contact',
    content: 'For questions about these Terms, contact: legal@void.ai'
  }
];

export default function TermsPage() {
  return (
    <PolicyLayout
      icon={<FileText className="w-5 h-5" />}
      title="Terms and Conditions"
      effectiveDate="August 27, 2026"
      description="These Terms govern your use of the VOID platform. Please read them carefully."
      sections={sections}
      version="Terms and Conditions v1.0"
      accentColor="emerald"
    />
  );
}
